# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Categ: create, read, update, delete
  Task: create, read, update, delete
  User: create, read, update, delete
